sudo: false
language: node_js
node_js:
- '6'
- 'lts/*'
cache:
  directories:
    - node_modules
branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
before_script: "npm update"
before_deploy: "npm run build"
deploy:
  provider: npm
  email: apiteam@swagger.io
  skip_cleanup: true
  api_key:
    secure: "dQFLWzLR64s3dBXk2RCYfjv7hb0j5wEHguSS9T77tYaDo9nGuuysmmPC9eO+xZ4jenLuQm6nSz9ugjbt06QgW1wfmq5gC97tP8Nj+MXESP89cwbvItCBOfgnZUvmDfoHUxj7A3hbkvSgjqEFSm371Zr8/d26iF0YcN9ZmqTdLRQ="
  on:
    tags: true
    repo: swagger-api/swagger-js
    node: '6.9'
